### ISSUE TITLE
Bluetooth Connect to X3 Fails

### ISSUE THREAD

**Issue by blackboxembedded** [Insta360Develop/CameraSDK-Android#40]
Using the SDK demo I'm unable to use Bluetooth to connect to an X3 camera.  Eventually, the error code -14169 is returned in the UI.  Attached is a logcat from the connection attempt.

[sdk-android-ble-X3-logcat.txt](https://github.com/Insta360Develop/CameraSDK-Android/files/10665205/sdk-android-ble-X3-logcat.txt)

**Comment by EternalSoySauce** [comment]
Make sure the camera is not connected to another app. The camera can only make one connection at a time.

If this is the case, reboot the camera.

**Comment by blackboxembedded** [comment]
I've tried the following steps:
Reset the Camera to defaults.
Power off camera
Power on camera
Power off phone
Power on phone
Launch the SDK example and try the Bluetooth connection

I always get error -14169.

My phone is a Pixel 6 Pro running the latest updates.  No official Insta360 app was installed during these tests.

**Comment by Tianweihaihaihai** [comment]
pls update to 1.5.3, the problem is solved on this version

**Comment by uzair0cha** [comment]
@Tianweihaihaihai still unable to establish consistent connection after the update of Sdk. The sdk based application crashes after both connections are made

**Comment by blackboxembedded** [comment]
I'm able to use Bluetooth with the current SDK.
